### ISSUE TITLE
Page-Embedded Permission Control

### ISSUE THREAD

**Issue by andypaicu** [WICG/proposals#113]
## Introduction

The permission flow on the web is generally straightforward (varying slightly from user agent to user agent). However there are common scenarios where the user experience of this flow is not great:
* Often the user does not understand why a site is requesting a permission, and what value they might gain from granting access to the site.
* Often the user is engaged in a different task that has nothing to do with the permission requested by the site. In such cases the permission prompt is often seen as an annoyance preventing the user from doing what they want to do.
* Often the user makes a decision and later wishes to change their mind. This becomes difficult as it involves the user needing to discover the correct user agent settings UI surface where they can update their previous decision.
* Often the user is visually focusing on an area of the screen that is away from the permission prompt position.

Having an in-content dedicated HTML element that serves as the entry point for the permission flow would address these scenarios and significantly improve the UX of permission prompts on the web.

[Read the complete Explainer][explainer]. 

## Feedback

Please provide all feedback below.

[explainer]: https://github.com/andypaicu/PEPC/blob/main/explainer.md "Page Embedded Permission Control"

**Comment by AdamSobieski** [comment]
New markup and metadata could be useful for webpages to declare which permissions and configuration items that they want to present to end-users, e.g., in the menu system which opens from the [lock or tune icon](https://blog.chromium.org/2023/05/an-update-on-lock-icon.html).

A `<settings>` element could contain both `<permissions>` and `<configuration>` elements as, beyond toggle-switch permissions, configuration items could be declared and subsequently provided in a Web browser menu system, e.g., the one accessed via the lock or tune icon.

The following example intends to show how one could formulate a markup supporting extensible permissions and configuration items. Towards providing searchable permissions and configuration items (as seen in many operating systems and Web browsers), markup could resemble:

```xml
<html>
  <head>
    <settings>
      <permissions>
        <permission name="w3c.notifications" type="optional" scope="subdomain" />
        <permission name="w3c.camera" type="optional" scope="page" />
        <permission name="w3c.microphone" type="required" scope="page" />
        <permission name="custom" type="optional" scope="page">
          <title>A Custom Permission</title>
          <keywords>...</keywords>
          <description>...</description>
        </permission>
      </permissions>
      <configuration>
        <item name="w3c.color-scheme" />
        <item name="custom">
          <title>Hue</title>
          <keywords>...</keywords>
          <description>...</description>
          <select>
            <option value="red">Red</option>
            <option value="green">Green</option>
            <option value="blue">Blue</option>
          </select>
        </item>
      </configuration>
    </settings>
  </head>
  <body>
    ...
  </body>
</html>
```

Above, a standard configuration item is depicted named "w3c.color-scheme" (observing that color scheme is a [media query property](https://www.w3.org/TR/mediaqueries-5/#prefers-color-scheme)) and a custom item is depicted, in this case for hue.

As envisioned: (1) only those permissions and configuration items declared in a `<settings>` element would need to be displayed for end-users, or others could be displayed as inactive, and (2) only those permissions and configuration items declared in a `<settings>` element could be accessed with JavaScript. However, these two points might not be backwards compatible with the existing permissions system.

`<settings>` elements could access remote resources instead of having to provide inline content.

```xml
<html>
  <head>
    <settings src="file.xml" />
  </head>
  <body>
    ...
  </body>
</html>
```

Instead of or in addition to XML, JSON could be explored for these purposes.

```xml
<html>
  <head>
    <settings type="application/json" src="file.json" />
  </head>
  <body>
    ...
  </body>
</html>
```

Interestingly, the EULAs of pages and services can be obtainable for end-users via the lock or tune menu system. Perhaps relevant metadata could resemble:

```xml
<html>
  <head>
    <link rel="eula" hreflang="en" href="eula-2023.html" />
  </head>
  <body>
    ...
  </body>
</html>
```

Permissions and configuration items could link to one or [more than one](https://github.com/WICG/proposals/issues/92) explanatory (EULA) document, to sections thereof, and/or to highlighted contents therein:

```xml
<html>
  <head>
    <link rel="eula" hreflang="en" href="eula-2023.html" />
    <settings>
      <permissions>
        <permission name="w3c.notifications" type="optional" scope="subdomain" href="eula-2023.html#notifications" />
        <permission name="w3c.camera" type="optional" scope="page" href="eula-2023.html#camera" />
        <permission name="w3c.microphone" type="required" scope="page" href="eula-2023.html#microphone" />
        <permission name="custom" type="optional" scope="page" href="eula-2023.html#acustompermission">
          <title>A Custom Permission</title>
          <keywords>...</keywords>
          <description>...</description>
        </permission>
      </permissions>
      <configuration>
        <item name="w3c.color-scheme" />
        <item name="custom">
          <title>Hue</title>
          <keywords>...</keywords>
          <description>...</description>
          <select>
            <option value="red">Red</option>
            <option value="green">Green</option>
            <option value="blue">Blue</option>
          </select>
        </item>
      </configuration>
    </settings>
  </head>
  <body>
    ...
  </body>
</html>
```

Further topics to consider include providing hints pertaining to nested directory structure for menus and submenus of permissions and configuration items. Noteworthy is that Web browsers could place settings and configuration items in lock or tune icon menu systems or elsewhere in other Web browser menu systems.

---

Combining these ideas with those in [the explainer](https://github.com/andypaicu/PEPC/blob/main/explainer.md), it could be a permission on lock or tune icon menu systems to authorize a webpage or service to be able to utilize page-embedded permission controls.

```xml
<html>
  <head>
    <link rel="eula" hreflang="en" href="eula-2023.html" />
    <settings>
      <permissions>
        <permission name="w3c.pepc" type="optional" scope="subdomain" />
        <permission name="w3c.notifications" type="optional" scope="subdomain" href="eula-2023.html#notifications" />
      </permissions>
    </settings>
  </head>
  <body>
    <p>
      Another use of the permission element could be in documents for interacting with the permissions system.
      Here is a permission element: <permission name="w3c.notifications" />.
      Permission elements might have :enabled and :disabled states for styling.
      To be enabled, permission elements would require "w3c.pepc" permission and for the permission that they
      allow interaction with to be declared in settings.
    </p>
  </body>
</html>
```

---

P.S.: On the topic of the lock or tune icon, https://github.com/WICG/proposals/issues/104 broaches that webpages and their media elements, e.g., images and videos, could be digitally signed and that so doing could benefit end-users with respect to ascertaining content provenance and authenticity. In this approach, webpages' contents' digital signatures and digitally-signed metadata could be inspected via the lock or tune icon.

**Comment by yoavweiss** [comment]
Looks great! Feel free to transfer the repo to me and I can take it from here

**Comment by andypaicu** [comment]
Thank you, transferred.
