### ISSUE TITLE
Proposal: Shared Element Transitions

### ISSUE THREAD

**Issue by vmpstr** [WICG/proposals#12]
## Introduction

Currently, a smooth transition between activities is hard to accomplish in a Single-Page App, and is impossible to do so in a Multi-Page App. This is because although the animation language is expressive and powerful, coordinating different animations and DOM mutations is a difficult task.

We propose an API that is easy to adopt, with an explicit "prepare" and "transition" steps that allow the user-agent to do the bulk of the work of saving the current visual state and transitioning to the new state with an animated effect.

[Please see the complete explainer](https://github.com/vmpstr/shared-element-transitions/blob/main/README.md). 

## Feedback

I welcome feedback in this thread, but encourage you to file bugs in [this repo](https://github.com/vmpstr/shared-element-transitions/) in order to keep better track of any concerns raised.

[explainer]: https://github.com/vmpstr/shared-element-transitions/blob/main/README.md "Shared Element Transitions"

**Comment by sdras** [comment]
This proposal is very exciting! The web can appear dated compared to native mobile experiences, and some of this is due to the cognitive leaks incurred by forcing the user to remap the space upon every route change.

I explain this a bit more [in this talk](https://youtu.be/oailLVjKFII?t=625), and I explain how to [accomplish this with technologies like Nuxt currently](https://css-tricks.com/native-like-animations-for-page-transitions-on-the-web/). 

Having a true API would break down a lot of barriers for entry for people and keep our users focused on the task at hand.

The only feedback I would give on the API is that it would be nice if there was an effect that was a simple hook for custom animations as well. Thanks!

**Comment by cwilso** [comment]
New repo created: https://github.com/WICG/shared-element-transitions.
